version: "3"
services:
  keycloak1:
    image: ghcr.io/patrickbeam/keycloak-19.0.2:latest
    command: ["start"]
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_CACHE=ispn
      - JAVA_OPTS_APPEND=-Djgroups.dns.query=headless-keycloak
      - kc_hostname_url=http://keycloak.cloudmast.io
    networks:
      - keycloak
  keycloak2:
    image: ghcr.io/patrickbeam/keycloak-19.0.2:latest
    command: ["start"]
    ports:
      - "81:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_CACHE=ispn
      - JAVA_OPTS_APPEND=-Djgroups.dns.query=headless-keycloak
      - kc_hostname_url=http://keycloak2.cloudmast.io:81
    networks:
      - keycloak
networks:
  keycloak:
