version: "3"
services:
  keycloak1:
    build: .
    command:
      [
        "--verbose",
        "start",
        "--db postgres",
        "--db-url-host Your DB host name here",
        "--db-username username",
        "--db-password password",
        "-Dkeycloak.infinispan.ignoreSkipCacheStore=true"
      ]
    ports:
      - "80:8080"
    environment:
      - KC_PROXY=edge
      - KC_CACHE=ispn
      - JAVA_OPTS_APPEND='-Djgroups.dns.query=headless-keycloak'
      - kc_hostname_url=
    networks:
      - keycloak
  keycloak2:
    build: .
    command:
      [
        "--verbose",
        "start",
        "--db postgres",
        "--db-url-host Your DB host name here",
        "--db-username username",
        "--db-password password",
        "-Dkeycloak.infinispan.ignoreSkipCacheStore=true"
      ]
    ports:
      - "81:8080"
    environment:
      - KC_PROXY=edge
      - JAVA_OPTS_APPEND='-Djgroups.dns.query=headless-keycloak'
      - kc_hostname_url=
      - KC_CACHE=ispn
      - kc_hostname_url=
    networks:
      - keycloak
networks:
  keycloak:
    postgres:
      image: postgres:10.21
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=keycloak
      networks:
        - keycloak
